buttons:
  B:
    onPress: "ROTATE_WRIST_CW"
    onRelease: "STOP_WRIST"
    topic: "arm_commands/"
    onShiftPress:
    onShiftRelease:
    value:
    onShiftValue:
  Y:
    onPress: "CLOSE_NIPPER"
    onRelease: "STOP_NIPPER"
    topic: "arm_commands/"
    onShiftPress:
    onShiftRelease:
    value:
    onShiftValue:
  X:
    onPress: "ROTATE_WRIST_CCW"
    onRelease: "STOP_WRIST"
    topic: "arm_commands/"
    onShiftPress:
    onShiftRelease:
    value:
    onShiftValue:
  A:
    onPress: "OPEN_NIPPER"
    onRelease: "STOP_NIPPER"
    topic: "arm_commands/"
    onShiftPress:
    onShiftRelease:
    value:
    onShiftValue:
  View:
    onPress: "DEPTH_REFERENCE_UPDATE"
    onRelease:
    topic: "state_commands/"
    onShiftPress:
    onShiftRelease:
    value: 0.50
    onShiftValue: 
  Option: 
    onPress: "CHANGE_CONTROLLER_STATUS"
    onRelease:
    topic: "state_commands/"
    onShiftPress:
    onShiftRelease:
    value:
    onShiftValue:
  Start:
    onPress: "ARM_ROV"
    onRelease:
    topic: "state_commands/"
    onShiftPress:
    onShiftRelease:
    value:
    onShiftValue:
  LC:
    onPress: "WORK_MODE"
    onRelease:
    topic: "state_commands/"
    onShiftPress:
    onShiftRelease:
    value:
    onShiftValue:
  RC:
    onPress:
    onRelease:
    topic:
    onShiftPress:
    onShiftRelease:
    value:
    onShiftValue: 
  LB:
    onPress: "DEPTH_REFERENCE_OFFSET"
    onRelease:
    topic: "state_commands/"
    onShiftPress:
    onShiftRelease:
    value: 0.02
    onShiftValue:
  RB:
    onPress: "DEPTH_REFERENCE_OFFSET"
    onRelease:
    topic: "state_commands/"
    onShiftPress:
    onShiftRelease:
    value: -0.02
    onShiftValue:
  D-Pad-Up:
    onPress: "PITCH_REFERENCE_OFFSET"
    onRelease: 
    topic: "state_commands/"
    onShiftPress:
    onShiftRelease:
    value: -2.0
    onShiftValue:
  D-Pad-Down:
    onPress: "PITCH_REFERENCE_OFFSET"
    onRelease:
    topic: "state_commands/"
    onShiftPress:
    onShiftRelease:
    value: 2.0
    onShiftValue:
  D-Pad-Left:
    onPress:
    onRelease:
    topic:
    onShiftPress:
    onShiftRelease:
    value:
    onShiftValue:
  D-Pad-Right:
    onPress:
    onRelease:
    topic:
    onShiftPress:
    onShiftRelease:
    value:
    onShiftValue:
  UPLOAD:
    onPress: "ABLE_ANGLE_CTL"
    onRelease:
    topic: "state_commands/"
    onShiftPress: "DISABLE_ANGLE_CTL"
    onShiftRelease:
    value:
    onShiftValue:
axes:
    LSB-X:
      command: "Y"
      deadzone: 2000
    LSB-Y: 
      command: "X"
      deadzone: 2000
    RSB-X: 
      command: "YAW"
      deadzone: 2000
    RSB-Y: 
      command: "PITCH"
      deadzone: 2000
    LT:
      command: "Z"
      deadzone: 500
    RT:
      command: "Z"
      deadzone: 500