buttons:
  B:
    onPress: "ROTATE_WRIST_CW"
    onRelease: "STOP_WRIST"
    topic: "arm_commands"
    onShiftRelease:
    onShiftPress:
    value:
    onShiftValue:
  Y:
    onPress: "CLOSE_NIPPER"
    onRelease: "STOP_NIPPER"
    topic: "arm_commands"
    onShiftRelease:
    onShiftPress:
    value:
    onShiftValue:
  X:
    onPress: "ROTATE_WRIST_CCW"
    onRelease: "STOP_WRIST"
    topic: "arm_commands"
    onShiftRelease: 
    onShiftPress:
    value:
    onShiftValue:
  A:
    onPress: "OPEN_NIPPER"
    onRelease: "STOP_NIPPER"
    topic: "arm_commands"
    onShiftRelease: 
    onShiftPress: 
    value:
    onShiftValue:
  View:
    onPress: "FREE"
    onRelease: "FREE"
    topic: "state_commands"
    onShiftRelease:
    onShiftPress:
    value: 10000
    onShiftValue: 0
  Option: 
    onPress: "TORQUE"
    onRelease: "TORQUE_OFF"
    topic: "state_commands"
    onShiftRelease:
    onShiftPress:
    value:
    onShiftValue:
  Start:
    onPress: "FREE"
    onRelease: "FREE"
    topic: "state_commands"
    onShiftRelease:
    onShiftPress:
    value:
    onShiftValue:
  LC:
    onPress: "FREE"
    onRelease: "FREE"
    topic:
    onShiftRelease: 
    onShiftPress:
    value:
    onShiftValue:
  RC:
    onPress: "FREE"
    onRelease: "FREE"
    topic: "arm_commands"
    onShiftRelease:
    onShiftPress:
    value: 10000
    onShiftValue: 
  LB:
    onPress: "YAW"
    onRelease: "YAW"
    topic: "state_commands"
    onShiftRelease: "YAW"
    onShiftPress: "YAW"
    value: -10000
    onShiftValue: -3000
  RB:
    onPress: "YAW"
    onRelease: "YAW"
    topic: "state_commands"
    onShiftRelease: "YAW"
    onShiftPress: "YAW"
    value: 10000
    onShiftValue: 3000
  D-Pad-Up:
    onPress: "ABLE_ANGLE_CTL"
    onRelease: 
    topic: "state_commands"
    onShiftRelease:
    onShiftPress:
    value: 10000
    onShiftValue:
  D-Pad-Down:
    onPress: "DISABLE_ANGLE_CTL"
    onRelease:
    topic: "state_commands"
    onShiftRelease:
    onShiftPress:
    value:
    onShiftValue:
  D-Pad-Left:
    onPress: "SHIFT"
    onRelease: "noSHIFT"
    topic: "state_commands"
    onShiftRelease: "noSHIFT"
    onShiftPress:
    value:
    onShiftValue:
  D-Pad-Right:
    onPress: "DPAD_RIGHT"
    onRelease: "FREE"
    topic: "state_commands"
    onShiftRelease:
    onShiftPress:
    value:
    onShiftValue:
  UPLOAD:
    onPress: "FREE"
    onRelease: "FREE"
    topic: "state_commands"
    onShiftRelease:
    onShiftPress:
    value:
    onShiftValue:
axes:
    LSB-X:
      command: "X"
      deadzone: 2000
    LSB-Y: 
      command: "Y"
      deadzone: 2000
    RSB-X: 
      command: "ROLL"
      deadzone: 2000
    RSB-Y: 
      command: "PITCH"
      deadzone: 2000
    LT:
      command: "Z"
      deadzone: 3000
    RT:
      command: "Z"
      deadzone: 3000